title: "vTomBlog"
tagline: "Oh look! A rabbit..."
description: "Rebuilt from WordPress export"
author: Tom
markdown: kramdown

url: "https://www.vtomblog.com"
baseurl: ""

collections:
  posts:
    output: true

minima:
  skin: classic
  social_links:
    github: virtualtom

sass:
  style: compressed
